#!/bin/sh
#
# DCENT_OS Amlogic MTD helper functions.

. /lib/functions/common.sh

DCENTOS_OFFSET_FROM_END_MTD0_TO_MTD1=0x600000
OFFSET_FROM_END_MTD0_TO_MTD1=$DCENTOS_OFFSET_FROM_END_MTD0_TO_MTD1

mtd_device_offset() {
    device_number="$1"
    device_name="mtd$device_number"
    res=0x0

    while read -r line; do
        [ "$line" = "dev:    size   erasesize  name" ] && continue
        device=$(echo "$line" | awk '{print $1}')
        size=$(echo "$line" | awk '{print "0x"$2}')
        [ "$device" = "$device_name:" ] && break
        res=$(printf "0x%X" $(($res + $size)))
    done < /proc/mtd

    if [ "$device_name" != "mtd0" ]; then
        res=$(printf "0x%X" $(($res + $DCENTOS_OFFSET_FROM_END_MTD0_TO_MTD1)))
    fi
    echo "$res"
}

mtd_local_offset() {
    mtd_partition_global_offset="$1"
    global_offset="$2"
    printf "0x%X" $(($global_offset - $mtd_partition_global_offset))
}

mtd_number_by_name() {
    name="$1"
    number=$(sed -E -n "s/mtd([0-9]+).*\"$name\"/\1/p" /proc/mtd)
    [ -n "$number" ] || return 1
    echo "$number"
}

if DCENTOS_SYSTEM_MTD_NUMBER=$(mtd_number_by_name "$DCENTOS_SYSTEM_MTD_NAME" 2>/dev/null); then
    DCENTOS_SYSTEM_MTD="/dev/mtd$DCENTOS_SYSTEM_MTD_NUMBER"
    DCENTOS_GLOBAL_SYSTEM_OFFSET=$(mtd_device_offset "$DCENTOS_SYSTEM_MTD_NUMBER")

    DCENTOS_LOCAL_UBOOT_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_UBOOT_OFFSET")
    DCENTOS_LOCAL_DTB_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_DTB_OFFSET")
    DCENTOS_LOCAL_KERNEL_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_KERNEL_OFFSET")
    DCENTOS_LOCAL_ROOTFS_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_ROOTFS_OFFSET")
    DCENTOS_LOCAL_RO_ENV_TAR_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_RO_ENV_TAR_OFFSET")
    DCENTOS_LOCAL_RO_ENV_TAR_LENGTH_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_RO_ENV_TAR_LENGTH_OFFSET")
    DCENTOS_LOCAL_RO_BACKUP_NAND_ENV_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_RO_NAND_ENV_OFFSET")
    DCENTOS_LOCAL_RECOVERY_FLAGS_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_RW_FLAGS_OFFSET")
    DCENTOS_LOCAL_RO_POST_INSTALL_TAR_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_RO_POST_INSTALL_TAR_OFFSET")
    DCENTOS_LOCAL_RO_POST_INSTALL_TAR_LENGTH_OFFSET=$(mtd_local_offset "$DCENTOS_GLOBAL_SYSTEM_OFFSET" "$DCENTOS_GLOBAL_RO_POST_INSTALL_TAR_LENGTH_OFFSET")

    BOS_SYSTEM_MTD_NUMBER=$DCENTOS_SYSTEM_MTD_NUMBER
    BOS_SYSTEM_MTD=$DCENTOS_SYSTEM_MTD
    GLOBAL_BOS_SYSTEM_OFFSET=$DCENTOS_GLOBAL_SYSTEM_OFFSET
    LOCAL_BOS_UBOOT_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_UBOOT_OFFSET
    LOCAL_BOS_DTB_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_DTB_OFFSET
    LOCAL_BOS_KERNEL_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_KERNEL_OFFSET
    LOCAL_BOS_ROOTFS_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_ROOTFS_OFFSET
    LOCAL_RO_ENV_TAR_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_RO_ENV_TAR_OFFSET
    LOCAL_RO_ENV_TAR_LENGTH_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_RO_ENV_TAR_LENGTH_OFFSET
    LOCAL_RO_BACKUP_NAND_ENV_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_RO_BACKUP_NAND_ENV_OFFSET
    LOCAL_RECOVERY_FLAGS_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_RECOVERY_FLAGS_OFFSET
    LOCAL_RO_POST_INSTALL_TAR_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_RO_POST_INSTALL_TAR_OFFSET
    LOCAL_RO_POST_INSTALL_TAR_LENGTH_OFFSET_BOS_LAYOUT=$DCENTOS_LOCAL_RO_POST_INSTALL_TAR_LENGTH_OFFSET
fi

if DCENTOS_OVERLAY_MTD_NUMBER=$(mtd_number_by_name "$DCENTOS_OVERLAY_MTD_NAME" 2>/dev/null); then
    DCENTOS_OVERLAY_MTD="/dev/mtd$DCENTOS_OVERLAY_MTD_NUMBER"
    BOS_OVERLAY_MTD_NUMBER=$DCENTOS_OVERLAY_MTD_NUMBER
    BOS_OVERLAY_MTD=$DCENTOS_OVERLAY_MTD
fi

if DCENTOS_STOCK_CONFIG_MTD_NUMBER=$(mtd_number_by_name "$DCENTOS_ENV_STOCK_CONFIG" 2>/dev/null); then
    DCENTOS_STOCK_CONFIG_MTD="/dev/mtd$DCENTOS_STOCK_CONFIG_MTD_NUMBER"
    STOCK_CONFIG_MTD_NUMBER=$DCENTOS_STOCK_CONFIG_MTD_NUMBER
    STOCK_CONFIG_MTD=$DCENTOS_STOCK_CONFIG_MTD
fi
