#!/usr/bin/env bash
#
# stage_am2_sd_artifacts.sh — Validate / stage BraiinsOS-class boot artifacts
# for a complete AM2 S19j Pro SD image build (CE-410 residual prep).
#
# Does NOT build or sign the image. Does NOT bypass CE-410; it only checks
# that an operator-supplied --artifacts-dir is ready for
# build_am2_s19jpro_sd_disk_image.sh WITHOUT --allow-incomplete.
#
# Usage:
#   bash scripts/stage_am2_sd_artifacts.sh --artifacts-dir <src> [--output-dir <dst>]
#   bash scripts/stage_am2_sd_artifacts.sh --artifacts-dir <src> --check-only
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ARTIFACTS_DIR=""
OUTPUT_DIR=""
CHECK_ONLY=0

# Same stock-XIL denylist as build_am2_s19jpro_sd_disk_image.sh
STOCK_XIL_BOOT_MD5S="
f2cb2eaaf757c72946113ad13786afa0
730a6ad1566376381dee8a59ebab55d6
7f100b3b90461e718ac6c1de0eafa888
dbd17ba1a738647540073f29813de92f
acb2fcdbcebfcbb71b02f3d0614363ae
6bc79007d45c3b623756523c6ab903ba
"

usage() {
    cat <<EOF
Usage: $(basename "$0") --artifacts-dir <dir> [--output-dir <dir>] [--check-only]

  --artifacts-dir   Directory containing BOOT.bin, uImage, and DTB
  --output-dir      Copy validated artifacts here (default: artifacts-dir)
  --check-only      Validate only; do not copy or write manifest

Exit 0 if ready for a complete AM2 SD build; non-zero otherwise.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --artifacts-dir) ARTIFACTS_DIR="${2:?}"; shift 2 ;;
        --artifacts-dir=*) ARTIFACTS_DIR="${1#*=}"; shift ;;
        --output-dir) OUTPUT_DIR="${2:?}"; shift 2 ;;
        --output-dir=*) OUTPUT_DIR="${1#*=}"; shift ;;
        --check-only) CHECK_ONLY=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "ERROR: unknown arg: $1" >&2; usage >&2; exit 2 ;;
    esac
done

if [ -z "$ARTIFACTS_DIR" ]; then
    echo "ERROR: --artifacts-dir is required" >&2
    usage >&2
    exit 2
fi
if [ ! -d "$ARTIFACTS_DIR" ]; then
    echo "ERROR: artifacts dir not found: $ARTIFACTS_DIR" >&2
    exit 1
fi

if [ -z "$OUTPUT_DIR" ]; then
    OUTPUT_DIR="$ARTIFACTS_DIR"
fi

file_size() {
    if stat -c%s "$1" >/dev/null 2>&1; then
        stat -c%s "$1"
    else
        # macOS / BSD
        stat -f%z "$1" 2>/dev/null || wc -c <"$1"
    fi
}

file_md5() {
    if command -v md5sum >/dev/null 2>&1; then
        md5sum "$1" | awk '{print $1}'
    elif command -v md5 >/dev/null 2>&1; then
        md5 -q "$1"
    else
        echo ""
    fi
}

BOOT_SRC=""
for cand in BOOT.bin boot.bin BOOT.BIN; do
    if [ -f "$ARTIFACTS_DIR/$cand" ]; then
        BOOT_SRC="$ARTIFACTS_DIR/$cand"
        break
    fi
done

UIMAGE_SRC=""
[ -f "$ARTIFACTS_DIR/uImage" ] && UIMAGE_SRC="$ARTIFACTS_DIR/uImage"

DTB_SRC=""
for dtb in am2-s19jpro.dtb am2-s19j.dtb devicetree.dtb zynq-am2.dtb zynq-s19jpro.dtb; do
    if [ -f "$ARTIFACTS_DIR/$dtb" ]; then
        DTB_SRC="$ARTIFACTS_DIR/$dtb"
        break
    fi
done

UBOOT_SRC=""
[ -f "$ARTIFACTS_DIR/u-boot.img" ] && UBOOT_SRC="$ARTIFACTS_DIR/u-boot.img"

BITSTREAM_SRC=""
for b in system.bit bitstream.bit fpga_bitstream.bit; do
    if [ -f "$ARTIFACTS_DIR/$b" ]; then
        BITSTREAM_SRC="$ARTIFACTS_DIR/$b"
        break
    fi
done

errors=0

if [ -z "$BOOT_SRC" ]; then
    echo "ERROR: missing BOOT.bin (or boot.bin / BOOT.BIN)" >&2
    errors=1
else
    BOOT_SZ=$(file_size "$BOOT_SRC")
    if [ "$BOOT_SZ" -lt 20000 ] || [ "$BOOT_SZ" -gt 5000000 ]; then
        echo "ERROR: BOOT.bin size $BOOT_SZ outside 20KiB..5MiB valid Zynq range" >&2
        errors=1
    fi
    BOOT_MD5=$(file_md5 "$BOOT_SRC")
    if [ -n "$BOOT_MD5" ]; then
        case "$STOCK_XIL_BOOT_MD5S" in
            *"$BOOT_MD5"*)
                echo "ERROR: BOOT.bin md5 $BOOT_MD5 matches known stock XIL signed image" >&2
                echo "       Use BraiinsOS am1-s9 SD recovery boot.bin instead" >&2
                errors=1
                ;;
        esac
    fi
fi

if [ -z "$UIMAGE_SRC" ]; then
    echo "ERROR: missing uImage" >&2
    errors=1
fi

if [ -z "$DTB_SRC" ]; then
    echo "ERROR: missing DTB (am2-s19jpro.dtb / devicetree.dtb / zynq-am2.dtb / …)" >&2
    errors=1
fi

if [ "$errors" -ne 0 ]; then
    echo "stage_am2_sd_artifacts: NOT READY for complete AM2 SD build" >&2
    exit 1
fi

# Optional: uEnv.txt may be generated by builder; bitstream may come from default path.
has_uenv=false
[ -f "$ARTIFACTS_DIR/uEnv.txt" ] && has_uenv=true
has_bitstream=false
[ -n "$BITSTREAM_SRC" ] && has_bitstream=true
has_uboot=false
[ -n "$UBOOT_SRC" ] && has_uboot=true

echo "stage_am2_sd_artifacts: READY"
echo "  BOOT:      $BOOT_SRC ($(file_size "$BOOT_SRC") bytes)"
echo "  uImage:    $UIMAGE_SRC ($(file_size "$UIMAGE_SRC") bytes)"
echo "  DTB:       $DTB_SRC ($(file_size "$DTB_SRC") bytes)"
echo "  u-boot.img: ${UBOOT_SRC:-"(optional, absent)"}"
echo "  bitstream: ${BITSTREAM_SRC:-"(optional here; builder default OK)"}"
echo "  uEnv.txt:  $has_uenv (builder can synthesize)"

if [ "$CHECK_ONLY" -eq 1 ]; then
    exit 0
fi

mkdir -p "$OUTPUT_DIR"

# Resolve real paths so staging into the same directory is a no-op rename.
_abs() {
    # Portable: prefer realpath; fall back to cd/pwd
    if command -v realpath >/dev/null 2>&1; then
        realpath "$1"
    else
        (cd "$(dirname "$1")" && echo "$(pwd)/$(basename "$1")")
    fi
}
ART_ABS="$(_abs "$ARTIFACTS_DIR")"
OUT_ABS="$(_abs "$OUTPUT_DIR")"

_copy_or_link() {
    src=$1
    dst=$2
    if [ ! -f "$src" ]; then
        return 0
    fi
    if [ "$ART_ABS" = "$OUT_ABS" ]; then
        # Same directory: only rename if basename differs.
        src_base=$(basename "$src")
        dst_base=$(basename "$dst")
        if [ "$src_base" != "$dst_base" ] && [ ! -f "$dst" ]; then
            cp -f "$src" "$dst"
        fi
        return 0
    fi
    cp -f "$src" "$dst"
}

# Copy using stable names the builder expects
_copy_or_link "$BOOT_SRC" "$OUTPUT_DIR/BOOT.bin"
_copy_or_link "$UIMAGE_SRC" "$OUTPUT_DIR/uImage"
_copy_or_link "$DTB_SRC" "$OUTPUT_DIR/devicetree.dtb"
[ -n "$UBOOT_SRC" ] && _copy_or_link "$UBOOT_SRC" "$OUTPUT_DIR/u-boot.img"
if [ -n "$BITSTREAM_SRC" ]; then
    _copy_or_link "$BITSTREAM_SRC" "$OUTPUT_DIR/system.bit"
fi
if [ -f "$ARTIFACTS_DIR/uEnv.txt" ]; then
    _copy_or_link "$ARTIFACTS_DIR/uEnv.txt" "$OUTPUT_DIR/uEnv.txt"
fi

# Staging readiness manifest (NOT the image CE-410 manifest — that is produced by the builder)
cat >"$OUTPUT_DIR/artifacts.manifest.json" <<EOF
{
  "schema": "dcentos.am2_sd_artifacts_stage.v1",
  "ready_for_complete_build": true,
  "boot_bin": true,
  "uImage": true,
  "devicetree_dtb": true,
  "u_boot_img": $has_uboot,
  "bitstream_in_dir": $has_bitstream,
  "uEnv_txt": $has_uenv,
  "notes": [
    "BraiinsOS am1-s9-class BOOT.bin required; stock XIL BOOT refused by MD5 denylist",
    "Rootfs/squashfs comes from --payload-tar at build time, not this staging dir",
    "Image-level boot_artifacts_complete is asserted by build_am2_s19jpro_sd_disk_image.sh + CE-410"
  ]
}
EOF

echo "  staged to: $OUTPUT_DIR"
echo "  wrote:     $OUTPUT_DIR/artifacts.manifest.json"
exit 0
