import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

describe('API type provenance', () => {
  it('keeps hand-maintained DTOs labelled separately from generated capability types', () => {
    const types = readFileSync('src/api/types.ts', 'utf8');
    const capability = readFileSync('src/api/generated/capability.ts', 'utf8');

    expect(types).toContain('Hand-maintained REST DTOs');
    expect(types).not.toContain('Auto-generated from dcentrald-api/src/rest.rs contracts');
    expect(types).toContain("from './generated/capability'");
    expect(capability).toContain('Generated by projects/dcent-schema/scripts/generate_capability_ts.py');
  });
});
